AWSTemplateFormatVersion: 2010-09-09
Description: Cria uma instancia spot EC2 com o binario do Kafka para acesso ao MSK.

Parameters:
  KeyPairName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Can contain only ASCII characters.

Mappings:
  AWSRegionArch2AMI:
    sa-east-1:
      HVM64: ami-090006f29ecb2d79a

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
        ImageId: !FindInMap [ AWSRegionArch2AMI, !Ref 'AWS::Region' , HVM64 ]
        KeyName: !Ref KeyPairName
        InstanceType: t2.micro
        SecurityGroups:
        - !Ref KafkaClientSecurityGroup

        BlockDeviceMappings:
        -
          DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50
        -
          DeviceName: /dev/sdm
          Ebs:
            VolumeSize: 100
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe
            apt update -y
            apt install -y default-jre
            apt install -y wget
            su - ubuntu -c 'wget https://archive.apache.org/dist/kafka/2.8.1/kafka_2.12-2.8.1.tgz'
            su - ubuntu -c 'tar -xvzf kafka_2.12-2.8.1.tgz'
            su - ubuntu -c 'echo "pruuuu!" >> /home/ubuntu/pombo.txt'
  KafkaClientSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
Outputs:
  InstanceDNS:
    Description: O DNS publico da instancia criada
    Value: !GetAtt EC2Instance.PublicDnsName            